# Luftqualitäts-Analyse – Notebook

In [20]:
# %matplotlib inline  # optional in lokalen Jupyter-Umgebungen

## Datenquelle
Gib hier die Datenquelle an.

In [21]:
DATA_SOURCE_PATH_ = "./data/openaq.csv"

## Daten einlesen

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv(DATA_SOURCE_PATH_, sep=None, engine="python", encoding="utf-8", dtype=str)

# TODO: Daten einlesen vervollständigen
# TODO: git committen (git dazulernen und alles sichern!)

In [23]:
df.describe()

,﻿Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
count,61177,32031,61175,61107,61177,61177,61177,61177,61177,61050
unique,137,4464,13941,15210,13,147,6,13542,5013,122
top,CN,ONTARIO,市环保局,"-25.5956514035919, 27.1256297242044",NO2,eea,µg/m³,0.0,2021-08-09T13:00:00+02:00,China
freq,11098,239,150,69,11129,13050,44669,2660,9582,11098

In [24]:
df.head()

,﻿Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,ZA,Alfred Nzo,Luka,"-25.5077634717075, 27.1838594119125",PM10,South Africa,µg/m³,20.0,2023-04-25T01:00:00+02:00,South Africa
1,IN,NaN,"ICRISAT Patancheru, Hyderabad - TSPCB","17.5184, 78.278777",SO2,caaqm,µg/m³,8.9,2022-10-31T02:45:00+01:00,India
2,IT,via Cadello CAGLIARI - Cagliari (CA),CENCA1,"39.23583300015611, 9.115000000173477",SO2,eea,µg/m³,0.5123,2025-01-11T22:00:00+01:00,Italy
3,JP,NaN,南アルプス市鏡中條１６４２－２,"35.601667, 138.498611",NO2,japan-soramame,ppm,0.002,2024-09-23T09:00:00+02:00,Japan
4,KR,NaN,대불,"34.757839999999995, 126.452808",PM10,korea-air,µg/m³,24.0,2025-01-28T10:00:00+01:00,"Korea, Republic of"

## Daten vorverarbeiten

In [25]:
# TODO: Daten vorverarbeiten (soweit notwendig)

## Land und Parameter (Pollutant)
Setzen Sie hier Land und Pollutant.

In [26]:
#available_countries = sorted(df_typed[col_country_code].dropna().unique().tolist())
#available_pollutants = sorted(df_typed[col_pollutant].dropna().unique().tolist())
#print("Länder (erste 50):", available_countries[:50])
#print("Pollutants:", available_pollutants)

In [27]:
country_code = "DE"   # z.B. "DE", "FR", "US", "CN", ...
pollutant   = "NO2"   # z.B. "NO2", "PM2.5", "O3", ...